name: bottom_navigation
description: Bottom Navigation to show a menu at bottom of screen
version: 1.0.0+1
author: pahlevikun

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  utilities:
    path: ../../module_core/utilities

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: