name: utilities
description: Utilities module.
version: 1.0.0
author: pahlevikun

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  manifest:
    path: ../manifest
  intl: ^0.16.1
  rxdart: ^0.24.1
  google_fonts: ^1.1.1
  device_info: ^1.0.0
  package_info: ^0.4.3+2
  permission_handler: ^5.0.1+1
  connectivity: ^2.0.2
  fluttertoast: ^7.1.6
  google_maps_flutter: ^0.5.25+2
  geocoding: ^1.0.5
  location: ^3.0.1

flutter: