name: utilities
description: Utilities module.
version: 1.0.0
author: alza

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  manifest:
    path: ../manifest
  intl: ^0.16.1
  rxdart: ^0.24.1
  google_fonts: ^2.1.0
  device_info: ^1.0.0
  package_info: ^0.4.3+2
  permission_handler: ^5.0.1+1
  connectivity: ^2.0.2
  fluttertoast: ^7.1.6

flutter: