name: assets
description: assets generator.
version: 1.0.0
author: alza

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  args: ^2.1.1
  dart_style: ^2.0.1
  path: '>=0.9.0 <2.0.0'
  yaml: ^3.0.0
  recase: ^2.0.1
  build: ^2.0.2
  build_config: ^1.0.0

dev_dependencies:
  lint: ^1.0.0
