name: dots_indicator
description: Dots indicator to show progression of a PageView for example
version: 1.0.0+1
author: pahlevikun

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: