name: introduction
description: Introduction/Onboarding package for flutter app with some customizations possibilities
version: 1.0.0+1
author: pahlevikun

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dots_indicator:
    path: ../dots_indicator

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: