name: flutter_music
description: a apps music creted with flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  video_player: ^2.0.2
  injectable: ^1.4.1
  http: ^0.13.1
  get_it: ^7.0.0
  dio: ^4.0.0-prev2
  retrofit: ^2.0.0
  json_serializable: ^4.1.3
  json_annotation:
  fluro: ^2.0.3
  flutter_bloc: ^7.0.1
  freezed: ^0.14.2
  equatable: ^2.0.3
  async: ^2.4.2
  retry: ^3.0.1
  states_rebuilder: ^4.3.0
  rxdart: ^0.27.1
  google_fonts: ^2.1.0
  device_info: ^2.0.2
  package_info: ^2.0.2
  permission_handler: ^8.1.2
  connectivity: ^3.0.6
  fluttertoast: ^8.0.7

  #  Local Modules
  manifest:
    path: ./module_core/manifest
  utilities:
    path: ./module_core/utilities


dev_dependencies:
  flutter_test:
    sdk: flutter
  network_image_mock: ^2.0.0
  retrofit_generator: ^2.0.0+3
  build_runner: ^2.0.5
  injectable_generator: ^1.4.1

flutter:
  uses-material-design: true
